// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Footer from "./_Components/Footer/Footer";
// import Navbar from "./_Components/Navbar/Navbar";
// import "@fortawesome/fontawesome-free/css/all.min.css";
// import { Toaster } from "sonner";
// import SessionWrapper from "./_Components/Provider/SessionProviderWrapper"; 
// import { CartContextProvider } from "./cart/CartContext";
// import { WishlistProvider } from "./wishList/WishlistContext";

// const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
// const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Fresh Cart",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }: { children: React.ReactNode }) {
//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
//         <SessionWrapper>
//           <CartContextProvider>
//             <WishlistProvider>
//                <Navbar />
//           {children}
//           <Toaster position="top-right" richColors />
//           <Footer />
//             </WishlistProvider>
            
//           </CartContextProvider>
         
//         </SessionWrapper>
//       </body>
//     </html>
//   );
// }
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./_Components/Footer/Footer";
import Navbar from "./_Components/Navbar/Navbar";
import "@fortawesome/fontawesome-free/css/all.min.css";
import { Toaster } from "sonner";
import SessionWrapper from "./_Components/Provider/SessionProviderWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Fresh Cart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SessionWrapper>
          <Navbar />
          {children}
          <Toaster position="top-right" richColors />
          <Footer />
        </SessionWrapper>
      </body>
    </html>
  );
}